package com.example.dao.quartz;

import com.example.domain.quartz.NewQrtzScheduleJob;
import com.example.domain.quartz.NewQrtzScheduleJobExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewQrtzScheduleJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    long countByExample(NewQrtzScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    int deleteByExample(NewQrtzScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    int insert(NewQrtzScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    int insertSelective(NewQrtzScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    List<NewQrtzScheduleJob> selectByExample(NewQrtzScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    NewQrtzScheduleJob selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") NewQrtzScheduleJob record, @Param("example") NewQrtzScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    int updateByExample(@Param("record") NewQrtzScheduleJob record, @Param("example") NewQrtzScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    int updateByPrimaryKeySelective(NewQrtzScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    int updateByPrimaryKey(NewQrtzScheduleJob record);
}