package com.example.dao.quartz;

import com.example.domain.quartz.NewQrtzScheduleLog;
import com.example.domain.quartz.NewQrtzScheduleLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewQrtzScheduleLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    long countByExample(NewQrtzScheduleLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    int deleteByExample(NewQrtzScheduleLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    int insert(NewQrtzScheduleLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    int insertSelective(NewQrtzScheduleLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    List<NewQrtzScheduleLog> selectByExample(NewQrtzScheduleLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    NewQrtzScheduleLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") NewQrtzScheduleLog record, @Param("example") NewQrtzScheduleLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    int updateByExample(@Param("record") NewQrtzScheduleLog record, @Param("example") NewQrtzScheduleLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    int updateByPrimaryKeySelective(NewQrtzScheduleLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    int updateByPrimaryKey(NewQrtzScheduleLog record);
}