package com.example.domain.quartz;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class NewQrtzScheduleLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public NewQrtzScheduleLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNull() {
            addCriterion("real_name is null");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNotNull() {
            addCriterion("real_name is not null");
            return (Criteria) this;
        }

        public Criteria andRealNameEqualTo(String value) {
            addCriterion("real_name =", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotEqualTo(String value) {
            addCriterion("real_name <>", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThan(String value) {
            addCriterion("real_name >", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThanOrEqualTo(String value) {
            addCriterion("real_name >=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThan(String value) {
            addCriterion("real_name <", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThanOrEqualTo(String value) {
            addCriterion("real_name <=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLike(String value) {
            addCriterion("real_name like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotLike(String value) {
            addCriterion("real_name not like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameIn(List<String> values) {
            addCriterion("real_name in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotIn(List<String> values) {
            addCriterion("real_name not in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameBetween(String value1, String value2) {
            addCriterion("real_name between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotBetween(String value1, String value2) {
            addCriterion("real_name not between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andSpringIdIsNull() {
            addCriterion("spring_id is null");
            return (Criteria) this;
        }

        public Criteria andSpringIdIsNotNull() {
            addCriterion("spring_id is not null");
            return (Criteria) this;
        }

        public Criteria andSpringIdEqualTo(String value) {
            addCriterion("spring_id =", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdNotEqualTo(String value) {
            addCriterion("spring_id <>", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdGreaterThan(String value) {
            addCriterion("spring_id >", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdGreaterThanOrEqualTo(String value) {
            addCriterion("spring_id >=", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdLessThan(String value) {
            addCriterion("spring_id <", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdLessThanOrEqualTo(String value) {
            addCriterion("spring_id <=", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdLike(String value) {
            addCriterion("spring_id like", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdNotLike(String value) {
            addCriterion("spring_id not like", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdIn(List<String> values) {
            addCriterion("spring_id in", values, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdNotIn(List<String> values) {
            addCriterion("spring_id not in", values, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdBetween(String value1, String value2) {
            addCriterion("spring_id between", value1, value2, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdNotBetween(String value1, String value2) {
            addCriterion("spring_id not between", value1, value2, "springId");
            return (Criteria) this;
        }

        public Criteria andMethodNameIsNull() {
            addCriterion("method_name is null");
            return (Criteria) this;
        }

        public Criteria andMethodNameIsNotNull() {
            addCriterion("method_name is not null");
            return (Criteria) this;
        }

        public Criteria andMethodNameEqualTo(String value) {
            addCriterion("method_name =", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameNotEqualTo(String value) {
            addCriterion("method_name <>", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameGreaterThan(String value) {
            addCriterion("method_name >", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameGreaterThanOrEqualTo(String value) {
            addCriterion("method_name >=", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameLessThan(String value) {
            addCriterion("method_name <", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameLessThanOrEqualTo(String value) {
            addCriterion("method_name <=", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameLike(String value) {
            addCriterion("method_name like", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameNotLike(String value) {
            addCriterion("method_name not like", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameIn(List<String> values) {
            addCriterion("method_name in", values, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameNotIn(List<String> values) {
            addCriterion("method_name not in", values, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameBetween(String value1, String value2) {
            addCriterion("method_name between", value1, value2, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameNotBetween(String value1, String value2) {
            addCriterion("method_name not between", value1, value2, "methodName");
            return (Criteria) this;
        }

        public Criteria andOperaterTypeIsNull() {
            addCriterion("operater_type is null");
            return (Criteria) this;
        }

        public Criteria andOperaterTypeIsNotNull() {
            addCriterion("operater_type is not null");
            return (Criteria) this;
        }

        public Criteria andOperaterTypeEqualTo(String value) {
            addCriterion("operater_type =", value, "operaterType");
            return (Criteria) this;
        }

        public Criteria andOperaterTypeNotEqualTo(String value) {
            addCriterion("operater_type <>", value, "operaterType");
            return (Criteria) this;
        }

        public Criteria andOperaterTypeGreaterThan(String value) {
            addCriterion("operater_type >", value, "operaterType");
            return (Criteria) this;
        }

        public Criteria andOperaterTypeGreaterThanOrEqualTo(String value) {
            addCriterion("operater_type >=", value, "operaterType");
            return (Criteria) this;
        }

        public Criteria andOperaterTypeLessThan(String value) {
            addCriterion("operater_type <", value, "operaterType");
            return (Criteria) this;
        }

        public Criteria andOperaterTypeLessThanOrEqualTo(String value) {
            addCriterion("operater_type <=", value, "operaterType");
            return (Criteria) this;
        }

        public Criteria andOperaterTypeLike(String value) {
            addCriterion("operater_type like", value, "operaterType");
            return (Criteria) this;
        }

        public Criteria andOperaterTypeNotLike(String value) {
            addCriterion("operater_type not like", value, "operaterType");
            return (Criteria) this;
        }

        public Criteria andOperaterTypeIn(List<String> values) {
            addCriterion("operater_type in", values, "operaterType");
            return (Criteria) this;
        }

        public Criteria andOperaterTypeNotIn(List<String> values) {
            addCriterion("operater_type not in", values, "operaterType");
            return (Criteria) this;
        }

        public Criteria andOperaterTypeBetween(String value1, String value2) {
            addCriterion("operater_type between", value1, value2, "operaterType");
            return (Criteria) this;
        }

        public Criteria andOperaterTypeNotBetween(String value1, String value2) {
            addCriterion("operater_type not between", value1, value2, "operaterType");
            return (Criteria) this;
        }

        public Criteria andChangeBeforeIsNull() {
            addCriterion("change_before is null");
            return (Criteria) this;
        }

        public Criteria andChangeBeforeIsNotNull() {
            addCriterion("change_before is not null");
            return (Criteria) this;
        }

        public Criteria andChangeBeforeEqualTo(String value) {
            addCriterion("change_before =", value, "changeBefore");
            return (Criteria) this;
        }

        public Criteria andChangeBeforeNotEqualTo(String value) {
            addCriterion("change_before <>", value, "changeBefore");
            return (Criteria) this;
        }

        public Criteria andChangeBeforeGreaterThan(String value) {
            addCriterion("change_before >", value, "changeBefore");
            return (Criteria) this;
        }

        public Criteria andChangeBeforeGreaterThanOrEqualTo(String value) {
            addCriterion("change_before >=", value, "changeBefore");
            return (Criteria) this;
        }

        public Criteria andChangeBeforeLessThan(String value) {
            addCriterion("change_before <", value, "changeBefore");
            return (Criteria) this;
        }

        public Criteria andChangeBeforeLessThanOrEqualTo(String value) {
            addCriterion("change_before <=", value, "changeBefore");
            return (Criteria) this;
        }

        public Criteria andChangeBeforeLike(String value) {
            addCriterion("change_before like", value, "changeBefore");
            return (Criteria) this;
        }

        public Criteria andChangeBeforeNotLike(String value) {
            addCriterion("change_before not like", value, "changeBefore");
            return (Criteria) this;
        }

        public Criteria andChangeBeforeIn(List<String> values) {
            addCriterion("change_before in", values, "changeBefore");
            return (Criteria) this;
        }

        public Criteria andChangeBeforeNotIn(List<String> values) {
            addCriterion("change_before not in", values, "changeBefore");
            return (Criteria) this;
        }

        public Criteria andChangeBeforeBetween(String value1, String value2) {
            addCriterion("change_before between", value1, value2, "changeBefore");
            return (Criteria) this;
        }

        public Criteria andChangeBeforeNotBetween(String value1, String value2) {
            addCriterion("change_before not between", value1, value2, "changeBefore");
            return (Criteria) this;
        }

        public Criteria andChangeAfrerIsNull() {
            addCriterion("change_afrer is null");
            return (Criteria) this;
        }

        public Criteria andChangeAfrerIsNotNull() {
            addCriterion("change_afrer is not null");
            return (Criteria) this;
        }

        public Criteria andChangeAfrerEqualTo(String value) {
            addCriterion("change_afrer =", value, "changeAfrer");
            return (Criteria) this;
        }

        public Criteria andChangeAfrerNotEqualTo(String value) {
            addCriterion("change_afrer <>", value, "changeAfrer");
            return (Criteria) this;
        }

        public Criteria andChangeAfrerGreaterThan(String value) {
            addCriterion("change_afrer >", value, "changeAfrer");
            return (Criteria) this;
        }

        public Criteria andChangeAfrerGreaterThanOrEqualTo(String value) {
            addCriterion("change_afrer >=", value, "changeAfrer");
            return (Criteria) this;
        }

        public Criteria andChangeAfrerLessThan(String value) {
            addCriterion("change_afrer <", value, "changeAfrer");
            return (Criteria) this;
        }

        public Criteria andChangeAfrerLessThanOrEqualTo(String value) {
            addCriterion("change_afrer <=", value, "changeAfrer");
            return (Criteria) this;
        }

        public Criteria andChangeAfrerLike(String value) {
            addCriterion("change_afrer like", value, "changeAfrer");
            return (Criteria) this;
        }

        public Criteria andChangeAfrerNotLike(String value) {
            addCriterion("change_afrer not like", value, "changeAfrer");
            return (Criteria) this;
        }

        public Criteria andChangeAfrerIn(List<String> values) {
            addCriterion("change_afrer in", values, "changeAfrer");
            return (Criteria) this;
        }

        public Criteria andChangeAfrerNotIn(List<String> values) {
            addCriterion("change_afrer not in", values, "changeAfrer");
            return (Criteria) this;
        }

        public Criteria andChangeAfrerBetween(String value1, String value2) {
            addCriterion("change_afrer between", value1, value2, "changeAfrer");
            return (Criteria) this;
        }

        public Criteria andChangeAfrerNotBetween(String value1, String value2) {
            addCriterion("change_afrer not between", value1, value2, "changeAfrer");
            return (Criteria) this;
        }

        public Criteria andOperaterDateIsNull() {
            addCriterion("operater_date is null");
            return (Criteria) this;
        }

        public Criteria andOperaterDateIsNotNull() {
            addCriterion("operater_date is not null");
            return (Criteria) this;
        }

        public Criteria andOperaterDateEqualTo(Date value) {
            addCriterion("operater_date =", value, "operaterDate");
            return (Criteria) this;
        }

        public Criteria andOperaterDateNotEqualTo(Date value) {
            addCriterion("operater_date <>", value, "operaterDate");
            return (Criteria) this;
        }

        public Criteria andOperaterDateGreaterThan(Date value) {
            addCriterion("operater_date >", value, "operaterDate");
            return (Criteria) this;
        }

        public Criteria andOperaterDateGreaterThanOrEqualTo(Date value) {
            addCriterion("operater_date >=", value, "operaterDate");
            return (Criteria) this;
        }

        public Criteria andOperaterDateLessThan(Date value) {
            addCriterion("operater_date <", value, "operaterDate");
            return (Criteria) this;
        }

        public Criteria andOperaterDateLessThanOrEqualTo(Date value) {
            addCriterion("operater_date <=", value, "operaterDate");
            return (Criteria) this;
        }

        public Criteria andOperaterDateIn(List<Date> values) {
            addCriterion("operater_date in", values, "operaterDate");
            return (Criteria) this;
        }

        public Criteria andOperaterDateNotIn(List<Date> values) {
            addCriterion("operater_date not in", values, "operaterDate");
            return (Criteria) this;
        }

        public Criteria andOperaterDateBetween(Date value1, Date value2) {
            addCriterion("operater_date between", value1, value2, "operaterDate");
            return (Criteria) this;
        }

        public Criteria andOperaterDateNotBetween(Date value1, Date value2) {
            addCriterion("operater_date not between", value1, value2, "operaterDate");
            return (Criteria) this;
        }

        public Criteria andAbTestIsNull() {
            addCriterion("ab_test is null");
            return (Criteria) this;
        }

        public Criteria andAbTestIsNotNull() {
            addCriterion("ab_test is not null");
            return (Criteria) this;
        }

        public Criteria andAbTestEqualTo(String value) {
            addCriterion("ab_test =", value, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestNotEqualTo(String value) {
            addCriterion("ab_test <>", value, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestGreaterThan(String value) {
            addCriterion("ab_test >", value, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestGreaterThanOrEqualTo(String value) {
            addCriterion("ab_test >=", value, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestLessThan(String value) {
            addCriterion("ab_test <", value, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestLessThanOrEqualTo(String value) {
            addCriterion("ab_test <=", value, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestLike(String value) {
            addCriterion("ab_test like", value, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestNotLike(String value) {
            addCriterion("ab_test not like", value, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestIn(List<String> values) {
            addCriterion("ab_test in", values, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestNotIn(List<String> values) {
            addCriterion("ab_test not in", values, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestBetween(String value1, String value2) {
            addCriterion("ab_test between", value1, value2, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestNotBetween(String value1, String value2) {
            addCriterion("ab_test not between", value1, value2, "abTest");
            return (Criteria) this;
        }

        public Criteria andBigUidIsNull() {
            addCriterion("big_uid is null");
            return (Criteria) this;
        }

        public Criteria andBigUidIsNotNull() {
            addCriterion("big_uid is not null");
            return (Criteria) this;
        }

        public Criteria andBigUidEqualTo(Long value) {
            addCriterion("big_uid =", value, "bigUid");
            return (Criteria) this;
        }

        public Criteria andBigUidNotEqualTo(Long value) {
            addCriterion("big_uid <>", value, "bigUid");
            return (Criteria) this;
        }

        public Criteria andBigUidGreaterThan(Long value) {
            addCriterion("big_uid >", value, "bigUid");
            return (Criteria) this;
        }

        public Criteria andBigUidGreaterThanOrEqualTo(Long value) {
            addCriterion("big_uid >=", value, "bigUid");
            return (Criteria) this;
        }

        public Criteria andBigUidLessThan(Long value) {
            addCriterion("big_uid <", value, "bigUid");
            return (Criteria) this;
        }

        public Criteria andBigUidLessThanOrEqualTo(Long value) {
            addCriterion("big_uid <=", value, "bigUid");
            return (Criteria) this;
        }

        public Criteria andBigUidIn(List<Long> values) {
            addCriterion("big_uid in", values, "bigUid");
            return (Criteria) this;
        }

        public Criteria andBigUidNotIn(List<Long> values) {
            addCriterion("big_uid not in", values, "bigUid");
            return (Criteria) this;
        }

        public Criteria andBigUidBetween(Long value1, Long value2) {
            addCriterion("big_uid between", value1, value2, "bigUid");
            return (Criteria) this;
        }

        public Criteria andBigUidNotBetween(Long value1, Long value2) {
            addCriterion("big_uid not between", value1, value2, "bigUid");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeIsNull() {
            addCriterion("sub_login_channel_code is null");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeIsNotNull() {
            addCriterion("sub_login_channel_code is not null");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeEqualTo(String value) {
            addCriterion("sub_login_channel_code =", value, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeNotEqualTo(String value) {
            addCriterion("sub_login_channel_code <>", value, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeGreaterThan(String value) {
            addCriterion("sub_login_channel_code >", value, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeGreaterThanOrEqualTo(String value) {
            addCriterion("sub_login_channel_code >=", value, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeLessThan(String value) {
            addCriterion("sub_login_channel_code <", value, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeLessThanOrEqualTo(String value) {
            addCriterion("sub_login_channel_code <=", value, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeLike(String value) {
            addCriterion("sub_login_channel_code like", value, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeNotLike(String value) {
            addCriterion("sub_login_channel_code not like", value, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeIn(List<String> values) {
            addCriterion("sub_login_channel_code in", values, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeNotIn(List<String> values) {
            addCriterion("sub_login_channel_code not in", values, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeBetween(String value1, String value2) {
            addCriterion("sub_login_channel_code between", value1, value2, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeNotBetween(String value1, String value2) {
            addCriterion("sub_login_channel_code not between", value1, value2, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeIsNull() {
            addCriterion("login_channel_code is null");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeIsNotNull() {
            addCriterion("login_channel_code is not null");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeEqualTo(String value) {
            addCriterion("login_channel_code =", value, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeNotEqualTo(String value) {
            addCriterion("login_channel_code <>", value, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeGreaterThan(String value) {
            addCriterion("login_channel_code >", value, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeGreaterThanOrEqualTo(String value) {
            addCriterion("login_channel_code >=", value, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeLessThan(String value) {
            addCriterion("login_channel_code <", value, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeLessThanOrEqualTo(String value) {
            addCriterion("login_channel_code <=", value, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeLike(String value) {
            addCriterion("login_channel_code like", value, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeNotLike(String value) {
            addCriterion("login_channel_code not like", value, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeIn(List<String> values) {
            addCriterion("login_channel_code in", values, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeNotIn(List<String> values) {
            addCriterion("login_channel_code not in", values, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeBetween(String value1, String value2) {
            addCriterion("login_channel_code between", value1, value2, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeNotBetween(String value1, String value2) {
            addCriterion("login_channel_code not between", value1, value2, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNull() {
            addCriterion("brand_id is null");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNotNull() {
            addCriterion("brand_id is not null");
            return (Criteria) this;
        }

        public Criteria andBrandIdEqualTo(Integer value) {
            addCriterion("brand_id =", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotEqualTo(Integer value) {
            addCriterion("brand_id <>", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThan(Integer value) {
            addCriterion("brand_id >", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("brand_id >=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThan(Integer value) {
            addCriterion("brand_id <", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThanOrEqualTo(Integer value) {
            addCriterion("brand_id <=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdIn(List<Integer> values) {
            addCriterion("brand_id in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotIn(List<Integer> values) {
            addCriterion("brand_id not in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdBetween(Integer value1, Integer value2) {
            addCriterion("brand_id between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotBetween(Integer value1, Integer value2) {
            addCriterion("brand_id not between", value1, value2, "brandId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 03 15:14:54 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table new_qrtz_schedule_log
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}