package com.example.domain.quartz;

import java.util.Date;

public class NewQrtzScheduleJob {
    public static final int STATUS_RUNNING = 1;
    public static final int STATUS_NOT_RUNNING = 0;
    public static final int CONCURRENT_IS = 1;
    public static final int CONCURRENT_NOT = 0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_job.id
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_job.job_name
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_job.spring_id
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    private String springId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_job.job_status
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    private Integer jobStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_job.cron_expression
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    private String cronExpression;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_job.method_name
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    private String methodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_job.is_concurrent
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    private Integer isConcurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_job.ext_params
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    private String extParams;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_job.is_runing
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    private Integer isRuning;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_job.run_server_ip
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    private String runServerIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_job.run_time
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    private Long runTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_job.description
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_job.create_time
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_job.update_time
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_job.ab_test
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    private String abTest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_job.big_uid
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    private Long bigUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_job.sub_login_channel_code
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    private String subLoginChannelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_job.login_channel_code
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    private String loginChannelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_job.brand_id
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    private Integer brandId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_job.id
     *
     * @return the value of new_qrtz_schedule_job.id
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_job.id
     *
     * @param id the value for new_qrtz_schedule_job.id
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_job.job_name
     *
     * @return the value of new_qrtz_schedule_job.job_name
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_job.job_name
     *
     * @param jobName the value for new_qrtz_schedule_job.job_name
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_job.spring_id
     *
     * @return the value of new_qrtz_schedule_job.spring_id
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public String getSpringId() {
        return springId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_job.spring_id
     *
     * @param springId the value for new_qrtz_schedule_job.spring_id
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setSpringId(String springId) {
        this.springId = springId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_job.job_status
     *
     * @return the value of new_qrtz_schedule_job.job_status
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public Integer getJobStatus() {
        return jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_job.job_status
     *
     * @param jobStatus the value for new_qrtz_schedule_job.job_status
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setJobStatus(Integer jobStatus) {
        this.jobStatus = jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_job.cron_expression
     *
     * @return the value of new_qrtz_schedule_job.cron_expression
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_job.cron_expression
     *
     * @param cronExpression the value for new_qrtz_schedule_job.cron_expression
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_job.method_name
     *
     * @return the value of new_qrtz_schedule_job.method_name
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_job.method_name
     *
     * @param methodName the value for new_qrtz_schedule_job.method_name
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_job.is_concurrent
     *
     * @return the value of new_qrtz_schedule_job.is_concurrent
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public Integer getIsConcurrent() {
        return isConcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_job.is_concurrent
     *
     * @param isConcurrent the value for new_qrtz_schedule_job.is_concurrent
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setIsConcurrent(Integer isConcurrent) {
        this.isConcurrent = isConcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_job.ext_params
     *
     * @return the value of new_qrtz_schedule_job.ext_params
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public String getExtParams() {
        return extParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_job.ext_params
     *
     * @param extParams the value for new_qrtz_schedule_job.ext_params
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setExtParams(String extParams) {
        this.extParams = extParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_job.is_runing
     *
     * @return the value of new_qrtz_schedule_job.is_runing
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public Integer getIsRuning() {
        return isRuning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_job.is_runing
     *
     * @param isRuning the value for new_qrtz_schedule_job.is_runing
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setIsRuning(Integer isRuning) {
        this.isRuning = isRuning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_job.run_server_ip
     *
     * @return the value of new_qrtz_schedule_job.run_server_ip
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public String getRunServerIp() {
        return runServerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_job.run_server_ip
     *
     * @param runServerIp the value for new_qrtz_schedule_job.run_server_ip
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setRunServerIp(String runServerIp) {
        this.runServerIp = runServerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_job.run_time
     *
     * @return the value of new_qrtz_schedule_job.run_time
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public Long getRunTime() {
        return runTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_job.run_time
     *
     * @param runTime the value for new_qrtz_schedule_job.run_time
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setRunTime(Long runTime) {
        this.runTime = runTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_job.description
     *
     * @return the value of new_qrtz_schedule_job.description
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_job.description
     *
     * @param description the value for new_qrtz_schedule_job.description
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_job.create_time
     *
     * @return the value of new_qrtz_schedule_job.create_time
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_job.create_time
     *
     * @param createTime the value for new_qrtz_schedule_job.create_time
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_job.update_time
     *
     * @return the value of new_qrtz_schedule_job.update_time
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_job.update_time
     *
     * @param updateTime the value for new_qrtz_schedule_job.update_time
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_job.ab_test
     *
     * @return the value of new_qrtz_schedule_job.ab_test
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public String getAbTest() {
        return abTest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_job.ab_test
     *
     * @param abTest the value for new_qrtz_schedule_job.ab_test
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setAbTest(String abTest) {
        this.abTest = abTest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_job.big_uid
     *
     * @return the value of new_qrtz_schedule_job.big_uid
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public Long getBigUid() {
        return bigUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_job.big_uid
     *
     * @param bigUid the value for new_qrtz_schedule_job.big_uid
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setBigUid(Long bigUid) {
        this.bigUid = bigUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_job.sub_login_channel_code
     *
     * @return the value of new_qrtz_schedule_job.sub_login_channel_code
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public String getSubLoginChannelCode() {
        return subLoginChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_job.sub_login_channel_code
     *
     * @param subLoginChannelCode the value for new_qrtz_schedule_job.sub_login_channel_code
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setSubLoginChannelCode(String subLoginChannelCode) {
        this.subLoginChannelCode = subLoginChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_job.login_channel_code
     *
     * @return the value of new_qrtz_schedule_job.login_channel_code
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public String getLoginChannelCode() {
        return loginChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_job.login_channel_code
     *
     * @param loginChannelCode the value for new_qrtz_schedule_job.login_channel_code
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setLoginChannelCode(String loginChannelCode) {
        this.loginChannelCode = loginChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_job.brand_id
     *
     * @return the value of new_qrtz_schedule_job.brand_id
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_job.brand_id
     *
     * @param brandId the value for new_qrtz_schedule_job.brand_id
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }
}