package com.example.domain.quartz;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class NewQrtzScheduleJobExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public NewQrtzScheduleJobExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNull() {
            addCriterion("job_name is null");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNotNull() {
            addCriterion("job_name is not null");
            return (Criteria) this;
        }

        public Criteria andJobNameEqualTo(String value) {
            addCriterion("job_name =", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotEqualTo(String value) {
            addCriterion("job_name <>", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThan(String value) {
            addCriterion("job_name >", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThanOrEqualTo(String value) {
            addCriterion("job_name >=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThan(String value) {
            addCriterion("job_name <", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThanOrEqualTo(String value) {
            addCriterion("job_name <=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLike(String value) {
            addCriterion("job_name like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotLike(String value) {
            addCriterion("job_name not like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameIn(List<String> values) {
            addCriterion("job_name in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotIn(List<String> values) {
            addCriterion("job_name not in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameBetween(String value1, String value2) {
            addCriterion("job_name between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotBetween(String value1, String value2) {
            addCriterion("job_name not between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andSpringIdIsNull() {
            addCriterion("spring_id is null");
            return (Criteria) this;
        }

        public Criteria andSpringIdIsNotNull() {
            addCriterion("spring_id is not null");
            return (Criteria) this;
        }

        public Criteria andSpringIdEqualTo(String value) {
            addCriterion("spring_id =", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdNotEqualTo(String value) {
            addCriterion("spring_id <>", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdGreaterThan(String value) {
            addCriterion("spring_id >", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdGreaterThanOrEqualTo(String value) {
            addCriterion("spring_id >=", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdLessThan(String value) {
            addCriterion("spring_id <", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdLessThanOrEqualTo(String value) {
            addCriterion("spring_id <=", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdLike(String value) {
            addCriterion("spring_id like", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdNotLike(String value) {
            addCriterion("spring_id not like", value, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdIn(List<String> values) {
            addCriterion("spring_id in", values, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdNotIn(List<String> values) {
            addCriterion("spring_id not in", values, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdBetween(String value1, String value2) {
            addCriterion("spring_id between", value1, value2, "springId");
            return (Criteria) this;
        }

        public Criteria andSpringIdNotBetween(String value1, String value2) {
            addCriterion("spring_id not between", value1, value2, "springId");
            return (Criteria) this;
        }

        public Criteria andJobStatusIsNull() {
            addCriterion("job_status is null");
            return (Criteria) this;
        }

        public Criteria andJobStatusIsNotNull() {
            addCriterion("job_status is not null");
            return (Criteria) this;
        }

        public Criteria andJobStatusEqualTo(Integer value) {
            addCriterion("job_status =", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusNotEqualTo(Integer value) {
            addCriterion("job_status <>", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusGreaterThan(Integer value) {
            addCriterion("job_status >", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("job_status >=", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusLessThan(Integer value) {
            addCriterion("job_status <", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusLessThanOrEqualTo(Integer value) {
            addCriterion("job_status <=", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusIn(List<Integer> values) {
            addCriterion("job_status in", values, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusNotIn(List<Integer> values) {
            addCriterion("job_status not in", values, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusBetween(Integer value1, Integer value2) {
            addCriterion("job_status between", value1, value2, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("job_status not between", value1, value2, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andCronExpressionIsNull() {
            addCriterion("cron_expression is null");
            return (Criteria) this;
        }

        public Criteria andCronExpressionIsNotNull() {
            addCriterion("cron_expression is not null");
            return (Criteria) this;
        }

        public Criteria andCronExpressionEqualTo(String value) {
            addCriterion("cron_expression =", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionNotEqualTo(String value) {
            addCriterion("cron_expression <>", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionGreaterThan(String value) {
            addCriterion("cron_expression >", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionGreaterThanOrEqualTo(String value) {
            addCriterion("cron_expression >=", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionLessThan(String value) {
            addCriterion("cron_expression <", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionLessThanOrEqualTo(String value) {
            addCriterion("cron_expression <=", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionLike(String value) {
            addCriterion("cron_expression like", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionNotLike(String value) {
            addCriterion("cron_expression not like", value, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionIn(List<String> values) {
            addCriterion("cron_expression in", values, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionNotIn(List<String> values) {
            addCriterion("cron_expression not in", values, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionBetween(String value1, String value2) {
            addCriterion("cron_expression between", value1, value2, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andCronExpressionNotBetween(String value1, String value2) {
            addCriterion("cron_expression not between", value1, value2, "cronExpression");
            return (Criteria) this;
        }

        public Criteria andMethodNameIsNull() {
            addCriterion("method_name is null");
            return (Criteria) this;
        }

        public Criteria andMethodNameIsNotNull() {
            addCriterion("method_name is not null");
            return (Criteria) this;
        }

        public Criteria andMethodNameEqualTo(String value) {
            addCriterion("method_name =", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameNotEqualTo(String value) {
            addCriterion("method_name <>", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameGreaterThan(String value) {
            addCriterion("method_name >", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameGreaterThanOrEqualTo(String value) {
            addCriterion("method_name >=", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameLessThan(String value) {
            addCriterion("method_name <", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameLessThanOrEqualTo(String value) {
            addCriterion("method_name <=", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameLike(String value) {
            addCriterion("method_name like", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameNotLike(String value) {
            addCriterion("method_name not like", value, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameIn(List<String> values) {
            addCriterion("method_name in", values, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameNotIn(List<String> values) {
            addCriterion("method_name not in", values, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameBetween(String value1, String value2) {
            addCriterion("method_name between", value1, value2, "methodName");
            return (Criteria) this;
        }

        public Criteria andMethodNameNotBetween(String value1, String value2) {
            addCriterion("method_name not between", value1, value2, "methodName");
            return (Criteria) this;
        }

        public Criteria andIsConcurrentIsNull() {
            addCriterion("is_concurrent is null");
            return (Criteria) this;
        }

        public Criteria andIsConcurrentIsNotNull() {
            addCriterion("is_concurrent is not null");
            return (Criteria) this;
        }

        public Criteria andIsConcurrentEqualTo(Integer value) {
            addCriterion("is_concurrent =", value, "isConcurrent");
            return (Criteria) this;
        }

        public Criteria andIsConcurrentNotEqualTo(Integer value) {
            addCriterion("is_concurrent <>", value, "isConcurrent");
            return (Criteria) this;
        }

        public Criteria andIsConcurrentGreaterThan(Integer value) {
            addCriterion("is_concurrent >", value, "isConcurrent");
            return (Criteria) this;
        }

        public Criteria andIsConcurrentGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_concurrent >=", value, "isConcurrent");
            return (Criteria) this;
        }

        public Criteria andIsConcurrentLessThan(Integer value) {
            addCriterion("is_concurrent <", value, "isConcurrent");
            return (Criteria) this;
        }

        public Criteria andIsConcurrentLessThanOrEqualTo(Integer value) {
            addCriterion("is_concurrent <=", value, "isConcurrent");
            return (Criteria) this;
        }

        public Criteria andIsConcurrentIn(List<Integer> values) {
            addCriterion("is_concurrent in", values, "isConcurrent");
            return (Criteria) this;
        }

        public Criteria andIsConcurrentNotIn(List<Integer> values) {
            addCriterion("is_concurrent not in", values, "isConcurrent");
            return (Criteria) this;
        }

        public Criteria andIsConcurrentBetween(Integer value1, Integer value2) {
            addCriterion("is_concurrent between", value1, value2, "isConcurrent");
            return (Criteria) this;
        }

        public Criteria andIsConcurrentNotBetween(Integer value1, Integer value2) {
            addCriterion("is_concurrent not between", value1, value2, "isConcurrent");
            return (Criteria) this;
        }

        public Criteria andExtParamsIsNull() {
            addCriterion("ext_params is null");
            return (Criteria) this;
        }

        public Criteria andExtParamsIsNotNull() {
            addCriterion("ext_params is not null");
            return (Criteria) this;
        }

        public Criteria andExtParamsEqualTo(String value) {
            addCriterion("ext_params =", value, "extParams");
            return (Criteria) this;
        }

        public Criteria andExtParamsNotEqualTo(String value) {
            addCriterion("ext_params <>", value, "extParams");
            return (Criteria) this;
        }

        public Criteria andExtParamsGreaterThan(String value) {
            addCriterion("ext_params >", value, "extParams");
            return (Criteria) this;
        }

        public Criteria andExtParamsGreaterThanOrEqualTo(String value) {
            addCriterion("ext_params >=", value, "extParams");
            return (Criteria) this;
        }

        public Criteria andExtParamsLessThan(String value) {
            addCriterion("ext_params <", value, "extParams");
            return (Criteria) this;
        }

        public Criteria andExtParamsLessThanOrEqualTo(String value) {
            addCriterion("ext_params <=", value, "extParams");
            return (Criteria) this;
        }

        public Criteria andExtParamsLike(String value) {
            addCriterion("ext_params like", value, "extParams");
            return (Criteria) this;
        }

        public Criteria andExtParamsNotLike(String value) {
            addCriterion("ext_params not like", value, "extParams");
            return (Criteria) this;
        }

        public Criteria andExtParamsIn(List<String> values) {
            addCriterion("ext_params in", values, "extParams");
            return (Criteria) this;
        }

        public Criteria andExtParamsNotIn(List<String> values) {
            addCriterion("ext_params not in", values, "extParams");
            return (Criteria) this;
        }

        public Criteria andExtParamsBetween(String value1, String value2) {
            addCriterion("ext_params between", value1, value2, "extParams");
            return (Criteria) this;
        }

        public Criteria andExtParamsNotBetween(String value1, String value2) {
            addCriterion("ext_params not between", value1, value2, "extParams");
            return (Criteria) this;
        }

        public Criteria andIsRuningIsNull() {
            addCriterion("is_runing is null");
            return (Criteria) this;
        }

        public Criteria andIsRuningIsNotNull() {
            addCriterion("is_runing is not null");
            return (Criteria) this;
        }

        public Criteria andIsRuningEqualTo(Integer value) {
            addCriterion("is_runing =", value, "isRuning");
            return (Criteria) this;
        }

        public Criteria andIsRuningNotEqualTo(Integer value) {
            addCriterion("is_runing <>", value, "isRuning");
            return (Criteria) this;
        }

        public Criteria andIsRuningGreaterThan(Integer value) {
            addCriterion("is_runing >", value, "isRuning");
            return (Criteria) this;
        }

        public Criteria andIsRuningGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_runing >=", value, "isRuning");
            return (Criteria) this;
        }

        public Criteria andIsRuningLessThan(Integer value) {
            addCriterion("is_runing <", value, "isRuning");
            return (Criteria) this;
        }

        public Criteria andIsRuningLessThanOrEqualTo(Integer value) {
            addCriterion("is_runing <=", value, "isRuning");
            return (Criteria) this;
        }

        public Criteria andIsRuningIn(List<Integer> values) {
            addCriterion("is_runing in", values, "isRuning");
            return (Criteria) this;
        }

        public Criteria andIsRuningNotIn(List<Integer> values) {
            addCriterion("is_runing not in", values, "isRuning");
            return (Criteria) this;
        }

        public Criteria andIsRuningBetween(Integer value1, Integer value2) {
            addCriterion("is_runing between", value1, value2, "isRuning");
            return (Criteria) this;
        }

        public Criteria andIsRuningNotBetween(Integer value1, Integer value2) {
            addCriterion("is_runing not between", value1, value2, "isRuning");
            return (Criteria) this;
        }

        public Criteria andRunServerIpIsNull() {
            addCriterion("run_server_ip is null");
            return (Criteria) this;
        }

        public Criteria andRunServerIpIsNotNull() {
            addCriterion("run_server_ip is not null");
            return (Criteria) this;
        }

        public Criteria andRunServerIpEqualTo(String value) {
            addCriterion("run_server_ip =", value, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpNotEqualTo(String value) {
            addCriterion("run_server_ip <>", value, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpGreaterThan(String value) {
            addCriterion("run_server_ip >", value, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpGreaterThanOrEqualTo(String value) {
            addCriterion("run_server_ip >=", value, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpLessThan(String value) {
            addCriterion("run_server_ip <", value, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpLessThanOrEqualTo(String value) {
            addCriterion("run_server_ip <=", value, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpLike(String value) {
            addCriterion("run_server_ip like", value, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpNotLike(String value) {
            addCriterion("run_server_ip not like", value, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpIn(List<String> values) {
            addCriterion("run_server_ip in", values, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpNotIn(List<String> values) {
            addCriterion("run_server_ip not in", values, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpBetween(String value1, String value2) {
            addCriterion("run_server_ip between", value1, value2, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunServerIpNotBetween(String value1, String value2) {
            addCriterion("run_server_ip not between", value1, value2, "runServerIp");
            return (Criteria) this;
        }

        public Criteria andRunTimeIsNull() {
            addCriterion("run_time is null");
            return (Criteria) this;
        }

        public Criteria andRunTimeIsNotNull() {
            addCriterion("run_time is not null");
            return (Criteria) this;
        }

        public Criteria andRunTimeEqualTo(Long value) {
            addCriterion("run_time =", value, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeNotEqualTo(Long value) {
            addCriterion("run_time <>", value, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeGreaterThan(Long value) {
            addCriterion("run_time >", value, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("run_time >=", value, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeLessThan(Long value) {
            addCriterion("run_time <", value, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeLessThanOrEqualTo(Long value) {
            addCriterion("run_time <=", value, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeIn(List<Long> values) {
            addCriterion("run_time in", values, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeNotIn(List<Long> values) {
            addCriterion("run_time not in", values, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeBetween(Long value1, Long value2) {
            addCriterion("run_time between", value1, value2, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeNotBetween(Long value1, Long value2) {
            addCriterion("run_time not between", value1, value2, "runTime");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andAbTestIsNull() {
            addCriterion("ab_test is null");
            return (Criteria) this;
        }

        public Criteria andAbTestIsNotNull() {
            addCriterion("ab_test is not null");
            return (Criteria) this;
        }

        public Criteria andAbTestEqualTo(String value) {
            addCriterion("ab_test =", value, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestNotEqualTo(String value) {
            addCriterion("ab_test <>", value, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestGreaterThan(String value) {
            addCriterion("ab_test >", value, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestGreaterThanOrEqualTo(String value) {
            addCriterion("ab_test >=", value, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestLessThan(String value) {
            addCriterion("ab_test <", value, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestLessThanOrEqualTo(String value) {
            addCriterion("ab_test <=", value, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestLike(String value) {
            addCriterion("ab_test like", value, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestNotLike(String value) {
            addCriterion("ab_test not like", value, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestIn(List<String> values) {
            addCriterion("ab_test in", values, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestNotIn(List<String> values) {
            addCriterion("ab_test not in", values, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestBetween(String value1, String value2) {
            addCriterion("ab_test between", value1, value2, "abTest");
            return (Criteria) this;
        }

        public Criteria andAbTestNotBetween(String value1, String value2) {
            addCriterion("ab_test not between", value1, value2, "abTest");
            return (Criteria) this;
        }

        public Criteria andBigUidIsNull() {
            addCriterion("big_uid is null");
            return (Criteria) this;
        }

        public Criteria andBigUidIsNotNull() {
            addCriterion("big_uid is not null");
            return (Criteria) this;
        }

        public Criteria andBigUidEqualTo(Long value) {
            addCriterion("big_uid =", value, "bigUid");
            return (Criteria) this;
        }

        public Criteria andBigUidNotEqualTo(Long value) {
            addCriterion("big_uid <>", value, "bigUid");
            return (Criteria) this;
        }

        public Criteria andBigUidGreaterThan(Long value) {
            addCriterion("big_uid >", value, "bigUid");
            return (Criteria) this;
        }

        public Criteria andBigUidGreaterThanOrEqualTo(Long value) {
            addCriterion("big_uid >=", value, "bigUid");
            return (Criteria) this;
        }

        public Criteria andBigUidLessThan(Long value) {
            addCriterion("big_uid <", value, "bigUid");
            return (Criteria) this;
        }

        public Criteria andBigUidLessThanOrEqualTo(Long value) {
            addCriterion("big_uid <=", value, "bigUid");
            return (Criteria) this;
        }

        public Criteria andBigUidIn(List<Long> values) {
            addCriterion("big_uid in", values, "bigUid");
            return (Criteria) this;
        }

        public Criteria andBigUidNotIn(List<Long> values) {
            addCriterion("big_uid not in", values, "bigUid");
            return (Criteria) this;
        }

        public Criteria andBigUidBetween(Long value1, Long value2) {
            addCriterion("big_uid between", value1, value2, "bigUid");
            return (Criteria) this;
        }

        public Criteria andBigUidNotBetween(Long value1, Long value2) {
            addCriterion("big_uid not between", value1, value2, "bigUid");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeIsNull() {
            addCriterion("sub_login_channel_code is null");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeIsNotNull() {
            addCriterion("sub_login_channel_code is not null");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeEqualTo(String value) {
            addCriterion("sub_login_channel_code =", value, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeNotEqualTo(String value) {
            addCriterion("sub_login_channel_code <>", value, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeGreaterThan(String value) {
            addCriterion("sub_login_channel_code >", value, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeGreaterThanOrEqualTo(String value) {
            addCriterion("sub_login_channel_code >=", value, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeLessThan(String value) {
            addCriterion("sub_login_channel_code <", value, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeLessThanOrEqualTo(String value) {
            addCriterion("sub_login_channel_code <=", value, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeLike(String value) {
            addCriterion("sub_login_channel_code like", value, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeNotLike(String value) {
            addCriterion("sub_login_channel_code not like", value, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeIn(List<String> values) {
            addCriterion("sub_login_channel_code in", values, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeNotIn(List<String> values) {
            addCriterion("sub_login_channel_code not in", values, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeBetween(String value1, String value2) {
            addCriterion("sub_login_channel_code between", value1, value2, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andSubLoginChannelCodeNotBetween(String value1, String value2) {
            addCriterion("sub_login_channel_code not between", value1, value2, "subLoginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeIsNull() {
            addCriterion("login_channel_code is null");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeIsNotNull() {
            addCriterion("login_channel_code is not null");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeEqualTo(String value) {
            addCriterion("login_channel_code =", value, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeNotEqualTo(String value) {
            addCriterion("login_channel_code <>", value, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeGreaterThan(String value) {
            addCriterion("login_channel_code >", value, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeGreaterThanOrEqualTo(String value) {
            addCriterion("login_channel_code >=", value, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeLessThan(String value) {
            addCriterion("login_channel_code <", value, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeLessThanOrEqualTo(String value) {
            addCriterion("login_channel_code <=", value, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeLike(String value) {
            addCriterion("login_channel_code like", value, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeNotLike(String value) {
            addCriterion("login_channel_code not like", value, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeIn(List<String> values) {
            addCriterion("login_channel_code in", values, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeNotIn(List<String> values) {
            addCriterion("login_channel_code not in", values, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeBetween(String value1, String value2) {
            addCriterion("login_channel_code between", value1, value2, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andLoginChannelCodeNotBetween(String value1, String value2) {
            addCriterion("login_channel_code not between", value1, value2, "loginChannelCode");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNull() {
            addCriterion("brand_id is null");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNotNull() {
            addCriterion("brand_id is not null");
            return (Criteria) this;
        }

        public Criteria andBrandIdEqualTo(Integer value) {
            addCriterion("brand_id =", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotEqualTo(Integer value) {
            addCriterion("brand_id <>", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThan(Integer value) {
            addCriterion("brand_id >", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("brand_id >=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThan(Integer value) {
            addCriterion("brand_id <", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThanOrEqualTo(Integer value) {
            addCriterion("brand_id <=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdIn(List<Integer> values) {
            addCriterion("brand_id in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotIn(List<Integer> values) {
            addCriterion("brand_id not in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdBetween(Integer value1, Integer value2) {
            addCriterion("brand_id between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotBetween(Integer value1, Integer value2) {
            addCriterion("brand_id not between", value1, value2, "brandId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 03 15:14:16 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table new_qrtz_schedule_job
     *
     * @mbg.generated Tue Dec 03 15:14:16 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}