package com.example.domain.quartz;

import java.util.Date;

public class NewQrtzScheduleLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_log.id
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_log.user_id
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_log.real_name
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_log.spring_id
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    private String springId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_log.method_name
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    private String methodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_log.operater_type
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    private String operaterType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_log.change_before
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    private String changeBefore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_log.change_afrer
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    private String changeAfrer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_log.operater_date
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    private Date operaterDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_log.ab_test
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    private String abTest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_log.big_uid
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    private Long bigUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_log.sub_login_channel_code
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    private String subLoginChannelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_log.login_channel_code
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    private String loginChannelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column new_qrtz_schedule_log.brand_id
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    private Integer brandId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_log.id
     *
     * @return the value of new_qrtz_schedule_log.id
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_log.id
     *
     * @param id the value for new_qrtz_schedule_log.id
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_log.user_id
     *
     * @return the value of new_qrtz_schedule_log.user_id
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_log.user_id
     *
     * @param userId the value for new_qrtz_schedule_log.user_id
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_log.real_name
     *
     * @return the value of new_qrtz_schedule_log.real_name
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_log.real_name
     *
     * @param realName the value for new_qrtz_schedule_log.real_name
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_log.spring_id
     *
     * @return the value of new_qrtz_schedule_log.spring_id
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public String getSpringId() {
        return springId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_log.spring_id
     *
     * @param springId the value for new_qrtz_schedule_log.spring_id
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public void setSpringId(String springId) {
        this.springId = springId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_log.method_name
     *
     * @return the value of new_qrtz_schedule_log.method_name
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_log.method_name
     *
     * @param methodName the value for new_qrtz_schedule_log.method_name
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_log.operater_type
     *
     * @return the value of new_qrtz_schedule_log.operater_type
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public String getOperaterType() {
        return operaterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_log.operater_type
     *
     * @param operaterType the value for new_qrtz_schedule_log.operater_type
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public void setOperaterType(String operaterType) {
        this.operaterType = operaterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_log.change_before
     *
     * @return the value of new_qrtz_schedule_log.change_before
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public String getChangeBefore() {
        return changeBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_log.change_before
     *
     * @param changeBefore the value for new_qrtz_schedule_log.change_before
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public void setChangeBefore(String changeBefore) {
        this.changeBefore = changeBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_log.change_afrer
     *
     * @return the value of new_qrtz_schedule_log.change_afrer
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public String getChangeAfrer() {
        return changeAfrer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_log.change_afrer
     *
     * @param changeAfrer the value for new_qrtz_schedule_log.change_afrer
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public void setChangeAfrer(String changeAfrer) {
        this.changeAfrer = changeAfrer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_log.operater_date
     *
     * @return the value of new_qrtz_schedule_log.operater_date
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public Date getOperaterDate() {
        return operaterDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_log.operater_date
     *
     * @param operaterDate the value for new_qrtz_schedule_log.operater_date
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public void setOperaterDate(Date operaterDate) {
        this.operaterDate = operaterDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_log.ab_test
     *
     * @return the value of new_qrtz_schedule_log.ab_test
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public String getAbTest() {
        return abTest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_log.ab_test
     *
     * @param abTest the value for new_qrtz_schedule_log.ab_test
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public void setAbTest(String abTest) {
        this.abTest = abTest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_log.big_uid
     *
     * @return the value of new_qrtz_schedule_log.big_uid
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public Long getBigUid() {
        return bigUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_log.big_uid
     *
     * @param bigUid the value for new_qrtz_schedule_log.big_uid
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public void setBigUid(Long bigUid) {
        this.bigUid = bigUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_log.sub_login_channel_code
     *
     * @return the value of new_qrtz_schedule_log.sub_login_channel_code
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public String getSubLoginChannelCode() {
        return subLoginChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_log.sub_login_channel_code
     *
     * @param subLoginChannelCode the value for new_qrtz_schedule_log.sub_login_channel_code
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public void setSubLoginChannelCode(String subLoginChannelCode) {
        this.subLoginChannelCode = subLoginChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_log.login_channel_code
     *
     * @return the value of new_qrtz_schedule_log.login_channel_code
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public String getLoginChannelCode() {
        return loginChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_log.login_channel_code
     *
     * @param loginChannelCode the value for new_qrtz_schedule_log.login_channel_code
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public void setLoginChannelCode(String loginChannelCode) {
        this.loginChannelCode = loginChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column new_qrtz_schedule_log.brand_id
     *
     * @return the value of new_qrtz_schedule_log.brand_id
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column new_qrtz_schedule_log.brand_id
     *
     * @param brandId the value for new_qrtz_schedule_log.brand_id
     *
     * @mbg.generated Tue Dec 03 15:14:54 CST 2019
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }
}