server:
  port: 1201
spring:
  application:
    name: example-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/hblixiaoming/config-server/
          username: hblixiaoming
          password: lxm87085332LXM
          search-paths: '{application}'
      discovery:
        enabled: true
        service-id: example-config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
