server:
  port: 1201
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hblixiaoming/config-server/
          username: hblixiaoming
          password: lxm87085332LXM
          search-paths: '{application}'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
